name: Tag Versioning

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure write access to the repository's contents
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Read VERSION
        id: read_version
        run: echo "version=$(cat VERSION.yaml)" >> $GITHUB_OUTPUT

      - name: Create Git tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "v${{ steps.getversion.outputs.version }}" -m "Tagging version v${{ steps.getversion.outputs.version }}"
          git push origin "v${{ steps.getversion.outputs.version }}"